In [29]:
import numpy as np

In [30]:
"""Write a function so that the columns of the output matrix are powers of the input
vector."""

def matrixVande(arr,yaxis,increasing=False):
    lst = list()
    xaxis = len(list(arr))
    for i in range(xaxis):
        for j in range(yaxis):
            if increasing == False:
                lst.append(arr[i]**(yaxis-j-1))
            else:
                lst.append(arr[i]**(j))
            
    mat = np.array(lst)
    return mat.reshape(xaxis,yaxis)

### Test cases for the function matrixVande

In [31]:
arr_sce_1, k_sce_1 = [1,2,3,5],3
arr_sce_2, k_sce_2 = [1,4],3
arr_sce_3, k_sce_3 = [1,5,10,15,20],5

display("Matrix generated with increasing as False")
display(matrixVande(arr_sce_1,k_sce_1))
display(matrixVande(arr_sce_2,k_sce_2))
display(matrixVande(arr_sce_3,k_sce_3))

display("Matrix generated with increasing as True")
display(matrixVande(arr_sce_1,k_sce_1,increasing = True))
display(matrixVande(arr_sce_2,k_sce_2,increasing = True))
display(matrixVande(arr_sce_3,k_sce_3,increasing = True))

'Matrix generated with increasing as False'

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

array([[ 1,  1,  1],
       [16,  4,  1]])

array([[     1,      1,      1,      1,      1],
       [   625,    125,     25,      5,      1],
       [ 10000,   1000,    100,     10,      1],
       [ 50625,   3375,    225,     15,      1],
       [160000,   8000,    400,     20,      1]])

'Matrix generated with increasing as True'

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  5, 25]])

array([[ 1,  1,  1],
       [ 1,  4, 16]])

array([[     1,      1,      1,      1,      1],
       [     1,      5,     25,    125,    625],
       [     1,     10,    100,   1000,  10000],
       [     1,     15,    225,   3375,  50625],
       [     1,     20,    400,   8000, 160000]])

In [32]:
"""Write a function to find moving average in an array over a window"""

def movingSeqGenerator(arr, window):
    sequence = list()
    arrLen = len(list(arr))
    for i in range(arrLen-window+1):
        sum = arr[i]
        for j in range(window-1):
            sum = sum + arr[i+j+1]
        sequence.append(sum/window)
        
    return sequence

### Test cases for the function movingSeqGenerator

In [33]:
display(movingSeqGenerator(range(10,101,10),4))
display(movingSeqGenerator([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3))

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]