In [1]:
import numpy as np

In [2]:
l = [3,4,5,6,'data','end']
ll = [[1,2],
      [3,4]]

### Conversion to array using numpy

#### Using the array() method

In [ ]:
arr1 = np.array(l)
darr = np.array(ll)

display(arr1)
display(np.array(l, ndmin = 4))
display(np.array([[2,3,4,5]]))
display(np.array([[[2,3,4,5]]]))
display(np.array([[2,3,4,5],[7,8,9,0]]))
display(arr1[0])
display(arr1[3::2])
display(darr[1][1])
display(darr[1,1])

#### Using the asarray() method

In [ ]:
display(np.asarray([3,4,5,6,7,8], dtype = np.float64))

#### Using the fromfunction() method

In [12]:
display(np.fromfunction(lambda i,j: i*j, (2,2), dtype = int))
display(np.fromfunction(lambda i,j,k: i+j+k, (2,2,3), dtype = int))
display(np.fromfunction(lambda i,j,k: i+j+k, (1,1,2), dtype = int))

array([[0, 0],
       [0, 1]])

array([[[0, 1, 2],
        [1, 2, 3]],

       [[1, 2, 3],
        [2, 3, 4]]])

array([[[0, 1]]])

#### Using the fromiter() and fromstring() method

In [ ]:
display(np.fromiter([1,2,3,4,5,6], dtype=int))

display(np.fromstring("1,2,3,4,5,6", sep=","))

#### Other methods

In [ ]:
darr1 = np.fromfunction(lambda i,j,k: i*j*k, (2,2,1), dtype = int)
ele1 = np.random.randint(2,10,(2,2))
ele2 = np.random.randint(2,10,(2,2))
ele3 = np.random.randint(2,10,(2,3))

display(darr1.ndim)
display(darr1.size)
display(darr1.shape)
display(darr1.dtype)
display(darr1.max())

display(np.arange(0,4.6,2.1))
display(np.linspace(1,5,10))
display(np.zeros(5))
display(np.zeros((2,4)))
display(np.ones(4))
display(np.ones((2,4)))
display(np.empty((2,3)))
# eye() method will generate a 2D array with 1 on the diagonal positions and 0 elsewhere
display(np.eye(5))
# generate a array of random given size
display(np.random.rand(2,3,3))
# generate a array of random given size whose mean will be 1 or standard deviation will be normal
display(np.random.randn(2,3,3))
display(np.random.randint(3,10, size = 10))
display(np.random.randint(3,10, (2,2)))
display(darr1.reshape(2,2))

#multiplication element wise
display(ele1*ele2)
#multiplication matrix type
display(ele1@ele2)

#rotate the array
display(ele3,ele3.T)

### Conversion to matrix using numpy

In [ ]:
mat1 = np.mat(np.random.randint(2,10,(2,2)))
mat2 = np.mat(np.random.randint(2,10,(2,2)))

display(np.mat([l]))
display(mat1)
display(mat2)
display(mat1*mat2)
display(mat1@mat2)

### Other numpy methods

In [ ]:
display(np.log10(ele1))
display(np.sqrt(ele1))
display(np.pi)